### ISSUE TITLE
Create a static content json file

### ISSUE THREAD

**Issue by aniquevered** [smaxwellstewart/monadicexploration#5]
Should follow same data structure as [https://github.com/smaxwellstewart/monadicexploration/blob/master/app/data.json](here), but with smtwordsarchive data

**Comment by kidtronnix** [comment]
This has been completed. We now have new sample data:

[data.json](https://github.com/smaxwellstewart/monadicexploration/blob/master/app/data.json)

The new data structure should be compatible with the original data structure, but has had the following fields added:

- `name` - name of contributor (optional)
- `tags` - hashtags of post. will be used to find links between posts. (will always be at least hashtag)
- `time` - time when person created post (generated automatically at post creation)
- `cdn` - url to where rich media is hosted (optional)

**Comment by kidtronnix** [comment]
@terribradley some sample data for you woop woop!
